name: Documentation

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install graphviz
        run: |
          sudo apt-get update
          sudo apt-get install graphviz
      - name: Set up Python 3.8
        uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: xarray
           environment-file: .binder/environment.yml
           python-version: 3.8
           auto-activate-base: false
      - name: Update conda environment
        shell: bash -l {0}
        run: conda env update --file ./ci/environment.yml
      - name: Deploy docs
        shell: bash -l {0}
        run: |
          set -e
          sphinx-build -M html . _build -v
          doctr deploy --built-docs _build/html .
